"""
VasudhaMithra — Regional & Bilingual Certificate Configuration Registry
Defines state-to-language mappings, ReportLab Indic font references, official
regional document titles, section headers, and field label translations.
Terminology reuses data/synthetic-generator/generate.py LANG_CONFIGS to ensure
strict end-to-end consistency between training synthetic data and outputs.
"""

from typing import Dict, Any

# Mandatory safety disclaimer required on every regional certificate
REGIONAL_SAFETY_DISCLAIMER = (
    "Digitization Platform Verification Certificate — Generated by VasudhaMithra, "
    "Not an Official Government-Issued Document."
)

REGIONAL_TEMPLATES: Dict[str, Dict[str, Any]] = {
    "Karnataka": {
        "language_code": "kn",
        "font_name": "NotoKannada",
        "system_name": "Bhoomi Land Records Management System",
        "state_header_local": "ಕರ್ನಾಟಕ ಸರ್ಕಾರ — ಕಂದಾಯ ಇಲಾಖೆ",
        "document_title_local": "ಪಹಣಿ (ಆರ್.ಟಿ.ಸಿ) / ಹಕ್ಕುಗಳ ದಾಖಲೆ",
        "document_title_en": "RECORD OF RIGHTS (RTC) / PAHANI EXTRACT",
        "accent_color": "#165B33",         # Bhoomi Emerald
        "accent_subtle": "#EBF7F2",
        "sections_local": {
            "land_details": "A. ಭೂಮಿಯ ವಿವರಗಳು / Land Details",
            "owner_details": "B. ಮಾಲೀಕರ ವಿವರ / Owner Details",
            "cultivation": "C. ಬೆಳೆ ವಿವರಗಳು / Cultivation Details",
            "assessment": "D. ತೆರಿಗೆ ಮತ್ತು ಮೌಲ್ಯಮಾಪನ / Tax & Assessment",
            "mutation": "E. ಮ್ಯೂಟೇಶನ್ ವಿವರ / Mutation Details",
            "boundaries": "F. ಗಡಿ ವಿವರ / Boundaries",
            "sketch": "G. ನಕ್ಷೆ / Cadastral Sketch (Not to Scale)",
            "other": "H. ಇತರೆ ಮಾಹಿತಿ / Other Information",
        },
        "field_labels_local": {
            "survey_number": "ಸರ್ವೆ ನಂ",
            "khasra_number": "ಖಸ್ರಾ ನಂ",
            "khata_number": "ಖಾತಾ ನಂ",
            "owner_name": "ಖಾತೇದಾರರ ಹೆಸರು",
            "plot_area": "ವಿಸ್ತೀರ್ಣ",
            "village": "ಗ್ರಾಮ",
            "tehsil": "ತಾಲೂಕು",
            "district": "ಜಿಲ್ಲೆ",
            "land_classification": "ಭೂ ವರ್ಗೀಕರಣ",
            "land_use": "ಭೂ ಬಳಕೆ",
            "mutation_number": "ಮ್ಯುಟೇಶನ್ ನಂ",
            "sub_division": "ಉಪ ವಿಭಾಗ",
            "father_husband_name": "ತಂದೆ / ಗಂಡನ ಹೆಸರು",
            "address": "ವಿಳಾಸ",
            "share": "ಪಾಲು",
            "ownership_type": "ಹಕ್ಕಿನ ಸ್ವರೂಪ",
            "year": "ವರ್ಷ",
            "season": "ಋತು",
            "crop": "ಬೆಳೆ",
            "irrigation_source": "ನೀರಾವರಿ ಮೂಲ",
            "yield": "ಉತ್ಪಾದನೆ",
            "remarks": "ಟಿಪ್ಪಣಿ",
            "land_revenue": "ಭೂಮಿ ತೆರಿಗೆ",
            "tax_cess": "ನೀರು / ಸೆಸ್ ತೆರಿಗೆ",
            "total_tax": "ಒಟ್ಟು",
            "tax_status": "ಸ್ಥಿತಿ",
            "north": "ಉತ್ತರ",
            "south": "ದಕ್ಷಿಣ",
            "east": "ಪೂರ್ವ",
            "west": "ಪಶ್ಚಿಮ",
        },
    },
    "Tamil Nadu": {
        "language_code": "ta",
        "font_name": "NotoTamil",
        "system_name": "tnreginet Directorate of Survey and Land Records",
        "state_header_local": "தமிழ்நாடு அரசு — வருவாய்த் துறை",
        "document_title_local": "பட்டா / சிட்டா / அடங்கல் பதிவு",
        "document_title_en": "PATTA / CHITTA / ADANGAL EXTRACT",
        "accent_color": "#1F487E",         # tnreginet Deep Blue
        "accent_subtle": "#EDF4FC",
        "sections_local": {
            "land_details": "A. நில விவரங்கள் / Land Details",
            "owner_details": "B. பட்டாதாரர் விவரங்கள் / Owner Details",
            "cultivation": "C. சாகுபடி விவரங்கள் / Cultivation Details",
            "assessment": "D. தீர்வை மற்றும் வரி விவரங்கள் / Assessment & Tax",
            "mutation": "E. பட்டா மாறுதல் விவரங்கள் / Mutation Details",
            "boundaries": "F. எல்லைகள் விவரம் / Boundaries",
            "sketch": "G. நில வரைபடம் / Cadastral Sketch (Not to Scale)",
            "other": "H. இதர விவரங்கள் / Other Information",
        },
        "field_labels_local": {
            "survey_number": "சர்வே எண்",
            "khasra_number": "கஸ்ரா எண்",
            "khata_number": "பட்டா எண்",
            "owner_name": "நில உரிமையாளர்",
            "plot_area": "நிலப் பரப்பளவு",
            "village": "கிராமம்",
            "tehsil": "வட்டம்",
            "district": "மாவட்டம்",
            "land_classification": "நில வகைப்பாடு",
            "land_use": "நில பயன்பாடு",
            "mutation_number": "மாறுதல் குறிப்பு எண்",
            "sub_division": "உட்பிரிவு எண்",
            "father_husband_name": "தந்தை / கணவர் பெயர்",
            "address": "முகவரி",
            "share": "பங்கு",
            "ownership_type": "உரிமை வகை",
            "year": "ஆண்டு",
            "season": "பருவம்",
            "crop": "பயிர்",
            "irrigation_source": "பாசன ஆதாரம்",
            "yield": "மகசூல்",
            "remarks": "குறிப்புகள்",
            "land_revenue": "நில வரி",
            "tax_cess": "பாசன வரி",
            "total_tax": "மொத்தம்",
            "tax_status": "நிலை",
            "north": "வடக்கு",
            "south": "தெற்கு",
            "east": "கிழக்கு",
            "west": "மேற்கு",
        },
    },
    "Telangana": {
        "language_code": "te",
        "font_name": "NotoTelugu",
        "system_name": "Dharani Integrated Land Records Management System",
        "state_header_local": "తెలంగాణ ప్రభుత్వం — రెవెన్యూ శాఖ",
        "document_title_local": "హక్కుల రికార్డు పట్టా (ROR) / పహణీ",
        "document_title_en": "RECORD OF RIGHTS (ROR) / PATTADAR EXTRACT",
        "accent_color": "#0B6E4F",         # Dharani Emerald
        "accent_subtle": "#E8F8F2",
        "sections_local": {
            "land_details": "1. భూమి వివరాలు / Land Details",
            "owner_details": "2. పట్టాదారు వివరాలు / Pattadar Details",
            "cultivation": "3. సాగు వివరాలు / Cultivation Details",
            "assessment": "4. శిస్తు & పన్ను వివరాలు / Assessment & Tax",
            "mutation": "5. మార్పిడి వివరాలు / Mutation Details",
            "boundaries": "6. సరిహద్దులు / Boundaries",
            "sketch": "7. భూ చిత్ర పటం / Cadastral Sketch (Not to Scale)",
            "other": "8. ఇతర గమనికలు / Other Remarks",
        },
        "field_labels_local": {
            "survey_number": "సర్వే నంబరు",
            "khasra_number": "ఖస్రా నంబరు",
            "khata_number": "ఖాతా నంబరు",
            "owner_name": "పట్టాదారు పేరు",
            "plot_area": "విస్తీర్ణం",
            "village": "గ్రామం",
            "tehsil": "మండలం",
            "district": "జిల్లా",
            "land_classification": "భూమి వర్గీకరణ",
            "land_use": "భూమి వినియోగం",
            "mutation_number": "మ్యుటేషన్ రిఫరెన్స్ నం",
            "sub_division": "ఉప విభాగం",
            "father_husband_name": "తండ్రి / భర్త పేరు",
            "address": "చిరునామా",
            "share": "పంపణీ వాటా",
            "ownership_type": "హక్కు రకం",
            "year": "సంవత్సరం",
            "season": "సీజన్",
            "crop": "పంట పేరు",
            "irrigation_source": "నీటి వనరు",
            "yield": "ఉత్పాదన",
            "remarks": "గమనికలు",
            "land_revenue": "భూమి శిస్తు",
            "tax_cess": "సాగునీటి పన్ను",
            "total_tax": "మొత్తం",
            "tax_status": "స్థితి",
            "north": "ఉత్తరం",
            "south": "దక్షిణం",
            "east": "తూర్పు",
            "west": "పడమర",
        },
    },
    "Andhra Pradesh": {
        "language_code": "te",
        "font_name": "NotoTelugu",
        "system_name": "Dharani / Meebhoomi Land Records Management System",
        "state_header_local": "ఆంధ్రప్రదేశ్ ప్రభుత్వం — రెవెన్యూ శాఖ",
        "document_title_local": "హక్కుల రికార్డు పట్టా (ROR) / అడంగల్",
        "document_title_en": "RECORD OF RIGHTS (ROR) / ADANGAL EXTRACT",
        "accent_color": "#0B6E4F",         # Meebhoomi Green
        "accent_subtle": "#E8F8F2",
        "sections_local": {
            "land_details": "1. భూమి వివరాలు / Land Details",
            "owner_details": "2. పట్టాదారు వివరాలు / Pattadar Details",
            "cultivation": "3. సాగు వివరాలు / Cultivation Details",
            "assessment": "4. శిస్తు & పన్ను వివరాలు / Assessment & Tax",
            "mutation": "5. మార్పిడి వివరాలు / Mutation Details",
            "boundaries": "6. సరిహద్దులు / Boundaries",
            "sketch": "7. భూ చిత్ర పటం / Cadastral Sketch (Not to Scale)",
            "other": "8. ఇతర గమనికలు / Other Remarks",
        },
        "field_labels_local": {
            "survey_number": "సర్వే నంబరు",
            "khasra_number": "ఖస్రా నంబరు",
            "khata_number": "ఖాతా నంబరు",
            "owner_name": "పట్టాదారు పేరు",
            "plot_area": "విస్తీర్ణం",
            "village": "గ్రామం",
            "tehsil": "మండలం",
            "district": "జిల్లా",
            "land_classification": "భూమి వర్గీకరణ",
            "land_use": "భూమి వినియోగం",
            "mutation_number": "మ్యుటేషన్ రిఫరెన్స్ నం",
            "sub_division": "ఉప విభాగం",
            "father_husband_name": "తండ్రి / భర్త పేరు",
            "address": "చిరునామా",
            "share": "పంపణీ వాటా",
            "ownership_type": "హక్కు రకం",
            "year": "సంవత్సరం",
            "season": "సీజన్",
            "crop": "పంట పేరు",
            "irrigation_source": "నీటి వనరు",
            "yield": "ఉత్పాదన",
            "remarks": "గమనికలు",
            "land_revenue": "భూమి శిస్తు",
            "tax_cess": "సాగునీటి పన్ను",
            "total_tax": "మొత్తం",
            "tax_status": "స్థితి",
            "north": "ఉత్తరం",
            "south": "దక్షిణం",
            "east": "తూర్పు",
            "west": "పడమర",
        },
    },
    "Maharashtra": {
        "language_code": "mr",
        "font_name": "NotoDevanagari",
        "system_name": "MahaBhulekh Land Records System",
        "state_header_local": "महाराष्ट्र शासन — महसूल विभाग",
        "document_title_local": "गाव नमुना ७/१२ (अधिकार अभिलेख)",
        "document_title_en": "RECORD OF RIGHTS (7/12 EXTRACT)",
        "accent_color": "#B84A1C",         # Mahabhulekh Terracotta
        "accent_subtle": "#FDF4ED",
        "sections_local": {
            "land_details": "A. जमिनीचा तपशील / Land Details",
            "owner_details": "B. खातेदारांचा तपशील / Owner Details",
            "cultivation": "C. पीक पाहणी तपशील / Crop Details",
            "assessment": "D. कर व महसूल तपशील / Assessment & Tax",
            "mutation": "E. फेरफार तपशील / Mutation Details",
            "boundaries": "F. चतुःसीमा / Boundaries",
            "sketch": "G. भू-नकाशा / Cadastral Sketch (Not to Scale)",
            "other": "H. इतर शेरा / Other Information",
        },
        "field_labels_local": {
            "survey_number": "सर्व्हे क्र / गट क्र",
            "khasra_number": "खसरा क्र",
            "khata_number": "खाते क्र",
            "owner_name": "खातेदाराचे नाव",
            "plot_area": "एकूण क्षेत्रफळ",
            "village": "गाव",
            "tehsil": "तालुका",
            "district": "जिल्हा",
            "land_classification": "जमीन प्रकार",
            "land_use": "जमीन वापर",
            "mutation_number": "फेरफार क्र",
            "sub_division": "उपविभाग क्र",
            "father_husband_name": "वडिलांचे / पतीचे नाव",
            "address": "पत्ता",
            "share": "हिस्सा",
            "ownership_type": "हक्काचे स्वरूप",
            "year": "वर्ष",
            "season": "हंगाम",
            "crop": "पीक",
            "irrigation_source": "पाण्याचा स्रोत",
            "yield": "उत्पादन",
            "remarks": "शेरा",
            "land_revenue": "जमीन महसूल",
            "tax_cess": "जलकर / उपकर",
            "total_tax": "एकूण",
            "tax_status": "स्थिती",
            "north": "उत्तर",
            "south": "दक्षिण",
            "east": "पूर्व",
            "west": "पश्चिम",
        },
    },
    "West Bengal": {
        "language_code": "bn",
        "font_name": "NotoBengali",
        "system_name": "Banglarbhumi Land & Land Reforms Department",
        "state_header_local": "পশ্চিমবঙ্গ সরকার — ভূমি ও ভূমি সংস্কার দপ্তর",
        "document_title_local": "খতিয়ান / পরচা (ROR)",
        "document_title_en": "RECORD OF RIGHTS (KHATIAN EXTRACT)",
        "accent_color": "#1D6A96",         # Banglarbhumi Blue
        "accent_subtle": "#EEF7FC",
        "sections_local": {
            "land_details": "A. জমির বিবরণ / Land Details",
            "owner_details": "B. রায়তের বিবরণ / Owner Details",
            "cultivation": "C. চাষের বিবরণ / Cultivation Details",
            "assessment": "D. কর ও রাজস্ব বিবরণ / Tax & Assessment",
            "mutation": "E. মিউটেশন বিবরণ / Mutation Details",
            "boundaries": "F. সীমানা বিবরণ / Boundaries",
            "sketch": "G. মৌজা নকশা / Cadastral Sketch (Not to Scale)",
            "other": "H. অন্যান্য মন্তব্য / Other Information",
        },
        "field_labels_local": {
            "survey_number": "দাগ নং",
            "khasra_number": "খসড়া নং",
            "khata_number": "খতিয়ান নং",
            "owner_name": "রায়তের নাম",
            "plot_area": "জমির পরিমাণ",
            "village": "মৌজা",
            "tehsil": "থানা / ব্লক",
            "district": "জেলা",
            "land_classification": "জমির শ্রেণি",
            "land_use": "জমির ব্যবহার",
            "mutation_number": "মিউটেশন কেস নং",
            "sub_division": "উপ-বিভাগ",
            "father_husband_name": "পিতা / স্বামীর নাম",
            "address": "ঠিকানা",
            "share": "অংশ",
            "ownership_type": "স্বত্বের ধরন",
            "year": "সাল",
            "season": "মৌসুম",
            "crop": "ফসল",
            "irrigation_source": "সেচ উৎস",
            "yield": "ফলন",
            "remarks": "মন্তব্য",
            "land_revenue": "খাজনা",
            "tax_cess": "সেচ কর / সেস",
            "total_tax": "মোট",
            "tax_status": "অবস্থা",
            "north": "উত্তর",
            "south": "দক্ষিণ",
            "east": "পূর্ব",
            "west": "পশ্চিম",
        },
    },
}

# Standard Default Template: Used for any unmapped state
# (e.g. Madhya Pradesh, Uttar Pradesh, Bihar, Rajasthan, Gujarat, Punjab, Haryana, etc.)
DEFAULT_HINDI_TEMPLATE: Dict[str, Any] = {
    "language_code": "hi",
    "font_name": "NotoDevanagari",
    "system_name": "State Revenue Department Land Records System",
    "state_header_local": "राज्य शासन — राजस्व विभाग",
    "document_title_local": "खसरा / अधिकार अभिलेख (ROR)",
    "document_title_en": "RECORD OF RIGHTS (ROR) / KHASRA EXTRACT",
    "accent_color": "#0B5B3E",             # Vasudha Forest Green
    "accent_subtle": "#FAF9F5",
    "sections_local": {
        "land_details": "A. भूमि विवरण / Land Details",
        "owner_details": "B. खातेदार विवरण / Owner Details",
        "cultivation": "C. फसल एवं कृषि विवरण / Crop & Cultivation",
        "assessment": "D. भू-राजस्व एवं कर / Assessment & Tax",
        "mutation": "E. नामांतरण विवरण / Mutation Details",
        "boundaries": "F. चौहद्दी / Boundaries",
        "sketch": "G. भू-नक्शा / Cadastral Sketch (Not to Scale)",
        "other": "H. अन्य टिप्पणी / Other Information",
    },
    "field_labels_local": {
        "survey_number": "सर्वे क्र",
        "khasra_number": "खसरा क्र",
        "khata_number": "खाता क्र",
        "owner_name": "खातेदार का नाम",
        "plot_area": "क्षेत्रफल (विस्तार)",
        "village": "ग्राम",
        "tehsil": "तहसील",
        "district": "जिला",
        "land_classification": "भूमि प्रकार",
        "land_use": "भूमि उपयोग",
        "mutation_number": "नामांतरण पंजी क्र",
        "sub_division": "उप संभाग",
        "father_husband_name": "पिता / पति का नाम",
        "address": "पता",
        "share": "हिस्सा",
        "ownership_type": "स्वामित्व प्रकार",
        "year": "वर्ष",
        "season": "मौसम",
        "crop": "फसल",
        "irrigation_source": "सिंचाई स्रोत",
        "yield": "उपज",
        "remarks": "टिप्पणी",
        "land_revenue": "भू-राजस्व",
        "tax_cess": "उपकर / जल कर",
        "total_tax": "कुल कर",
        "tax_status": "स्थिति",
        "north": "उत्तर",
        "south": "दक्षिण",
        "east": "पूर्व",
        "west": "पश्चिम",
    },
}


def get_regional_template(state_name: str | None) -> tuple[str, Dict[str, Any]]:
    """
    Resolves the regional certificate configuration based on the record's state.
    Matches exact or fuzzy state names (case-insensitive).
    Falls back gracefully to the standard Hindi/Devanagari template for any unmapped states.
    Returns (resolved_state_name, template_dict).
    """
    if not state_name or not isinstance(state_name, str):
        return "National", DEFAULT_HINDI_TEMPLATE

    clean_state = state_name.strip()

    # Exact match
    if clean_state in REGIONAL_TEMPLATES:
        return clean_state, REGIONAL_TEMPLATES[clean_state]

    # Case-insensitive / partial match
    state_lower = clean_state.lower()
    for key, tmpl in REGIONAL_TEMPLATES.items():
        if key.lower() == state_lower:
            return key, tmpl
        if key.lower() in state_lower or state_lower in key.lower():
            return key, tmpl

    # State not in explicit regional templates list (e.g. MP, UP, Bihar, etc.)
    # Fall back to Hindi/Devanagari default
    custom_default = dict(DEFAULT_HINDI_TEMPLATE)
    custom_default["state_header_local"] = f"{clean_state} शासन — राजस्व विभाग"
    return clean_state, custom_default


def resolve_record_template(
    language: str | None,
    state: str | None = None,
    fields: dict | None = None,
) -> tuple[str, Dict[str, Any]]:
    """
    Resolves the state and regional template matching the uploaded land record.
    Checks the uploaded record's language first, then state, then field hints.
    Returns (resolved_state_name, template_dict).
    """
    fields = fields or {}
    field_text = " ".join(str(v).lower() for v in fields.values())
    lang_clean = (language or "").strip().lower()
    state_clean = (state or "").strip()

    # If language is explicit Indic language
    if lang_clean == "kn":
        return "Karnataka", REGIONAL_TEMPLATES["Karnataka"]
    if lang_clean == "ta":
        return "Tamil Nadu", REGIONAL_TEMPLATES["Tamil Nadu"]
    if lang_clean == "te":
        if any(w in field_text or w in state_clean.lower() for w in ["andhra", "meebhoomi", "ఆంధ్రప్రదేశ్", "vizianagaram", "gajapathinagaram"]):
            return "Andhra Pradesh", REGIONAL_TEMPLATES["Andhra Pradesh"]
        return "Telangana", REGIONAL_TEMPLATES["Telangana"]
    if lang_clean == "mr":
        return "Maharashtra", REGIONAL_TEMPLATES["Maharashtra"]
    if lang_clean == "bn":
        return "West Bengal", REGIONAL_TEMPLATES["West Bengal"]
    if lang_clean == "hi":
        return "Madhya Pradesh", DEFAULT_HINDI_TEMPLATE

    # If state is provided
    if state_clean:
        return get_regional_template(state_clean)

    return "Karnataka", REGIONAL_TEMPLATES["Karnataka"]
